name: Deploy Angular to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Upload only modified files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: dist/oscarlaude.fr
          remoteDir: ${{ secrets.SFTP_TARGET_DIR }}
          options: --reverse --verbose --only-newer --exclude-glob 'assets/taiga-ui/**'

      - name: Post-deployment cleanup
        run: |
          echo "No further cleanup needed"
